td.tdlib.database-directory=tdlib
td.tdlib.files-directory=tdlib/files
td.tdlib.system-language-code=ru
td.tdlib.device-model=Java
td.tdlib.application-version=1.0.4-debug
td.lib-path=/home/oleg/td/build/libtdjson.so
td.use-test-dc=false
td.case-insensitive=true

server.address=0.0.0.0
server.port=8080

logging.pattern.console=[%thread] %5level %logger - %msg%n
