# TDLib Configuration
td.tdlib.api-id=20381407
td.tdlib.api-hash=0362bc360583fff1a6e35bbdf2083c6f
td.tdlib.database-directory=tdlib
td.tdlib.files-directory=tdlib/files
td.tdlib.system-language-code=ru
td.tdlib.device-model=Java
td.tdlib.application-version=1.0.4-debug

# ???????????
td.auth.phone=+375292223399
td.auth.code=
td.auth.pass=

# ??????
td.lib-path=/home/oleg/td/build/libtdjson.so
td.bot-username=
td.welcome-message=
td.use-test-dc=false
td.case-insensitive=true

# ?????? ?????
logging.pattern.console=[%thread] %5level %logger - %msg%n
